# Generated by Django 6.0.7 on 2026-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse_reservation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
