--
-- PostgreSQL database dump
--

\restrict ylVtSShaRtwu7foGSTklCN4vcufnOiIc0d0jC5uBr9XhsDT3MQrRyrgUv30NjkK

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: BookShop_book; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BookShop_book" (
    id bigint NOT NULL,
    title character varying(100) NOT NULL,
    author character varying(100) NOT NULL,
    price numeric(10,2),
    description text NOT NULL,
    stock integer NOT NULL,
    category_id bigint
);


--
-- Name: BookShop_book_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BookShop_book" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookShop_book_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BookShop_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BookShop_category" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL
);


--
-- Name: BookShop_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BookShop_category" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookShop_category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BookShop_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BookShop_user" (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username character varying(100),
    email character varying(254) NOT NULL,
    native_name character varying(5) NOT NULL,
    phone_number character varying(11) NOT NULL
);


--
-- Name: BookShop_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BookShop_user_groups" (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: BookShop_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BookShop_user_groups" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookShop_user_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BookShop_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BookShop_user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookShop_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BookShop_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BookShop_user_user_permissions" (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: BookShop_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BookShop_user_user_permissions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookShop_user_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Data for Name: BookShop_book; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."BookShop_book" (id, title, author, price, description, stock, category_id) FROM stdin;
1	Linux From Scratch	Джирард Бекманс	100.00	Способ установки Linux, а также книга Герарда Бикманса и др., описывающая процесс сборки своего дистрибутива операционной системы Linux из исходных кодов.	15	1
2	asdasd	aaa	100.00	asdads	50	1
3	aaaaaaaa	bbbbbbbb	\N	Some text xD	15	1
4	gagas	bbbbbb11	\N	Very interesting book	10	1
5	hhhhhhhhh	ccccccccc	86.00	jkkaadry	90	1
6	hhhhhhhhh	ccccccccc	86.00	jkkaadry	90	1
7	bbzxzxbX	llujhyu	\N	bla bla bla	92	1
8	gggg	lljka	\N	Yeah	32	1
9	fffff	fff	23.00	iii	78	1
\.


--
-- Data for Name: BookShop_category; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."BookShop_category" (id, name, slug) FROM stdin;
1	electronics	el
\.


--
-- Data for Name: BookShop_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."BookShop_user" (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, username, email, native_name, phone_number) FROM stdin;
1	pbkdf2_sha256$1200000$LZwZzpZl86YbkkkGBN044M$NOVNF9DuJk/pmrYIl8wIXjYQLqCAD4xVZZ+FEDSZow4=	\N	t			t	t	2026-05-25 03:21:39.391037+02	archrog	example@mail.com		
\.


--
-- Data for Name: BookShop_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."BookShop_user_groups" (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: BookShop_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."BookShop_user_user_permissions" (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add book	6	add_book
22	Can change book	6	change_book
23	Can delete book	6	delete_book
24	Can view book	6	view_book
25	Can add Category	7	add_category
26	Can change Category	7	change_category
27	Can delete Category	7	delete_category
28	Can view Category	7	view_category
29	Can add user	8	add_user
30	Can change user	8	change_user
31	Can delete user	8	delete_user
32	Can view user	8	view_user
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	BookShop	book
7	BookShop	category
8	BookShop	user
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	BookShop	0001_initial	2026-05-25 02:36:22.236912+02
2	BookShop	0002_book_category	2026-05-25 02:36:22.240982+02
3	BookShop	0003_alter_book_category	2026-05-25 02:36:22.249391+02
4	BookShop	0004_alter_category_options_alter_book_category_and_more	2026-05-25 02:36:22.255592+02
5	BookShop	0005_alter_book_price	2026-05-25 02:36:22.258002+02
6	contenttypes	0001_initial	2026-05-25 02:36:22.261136+02
7	contenttypes	0002_remove_content_type_name	2026-05-25 02:38:45.975327+02
8	auth	0001_initial	2026-05-25 02:38:45.989658+02
9	auth	0002_alter_permission_name_max_length	2026-05-25 02:38:45.992419+02
10	auth	0003_alter_user_email_max_length	2026-05-25 02:38:45.995108+02
11	auth	0004_alter_user_username_opts	2026-05-25 02:38:45.998198+02
12	auth	0005_alter_user_last_login_null	2026-05-25 02:38:46.001261+02
13	auth	0006_require_contenttypes_0002	2026-05-25 02:38:46.002297+02
14	auth	0007_alter_validators_add_error_messages	2026-05-25 02:38:46.005309+02
15	auth	0008_alter_user_username_max_length	2026-05-25 02:38:46.008518+02
16	auth	0009_alter_user_last_name_max_length	2026-05-25 02:38:46.010986+02
17	auth	0010_alter_group_name_max_length	2026-05-25 02:38:46.014585+02
18	auth	0011_update_proxy_permissions	2026-05-25 02:38:46.018377+02
19	auth	0012_alter_user_first_name_max_length	2026-05-25 02:38:46.021191+02
20	BookShop	0006_alter_book_options_user	2026-05-25 02:38:46.033068+02
21	admin	0001_initial	2026-05-25 02:38:46.040233+02
22	admin	0002_logentry_remove_auto_add	2026-05-25 02:38:46.04437+02
23	admin	0003_logentry_add_action_flag_choices	2026-05-25 02:38:46.048196+02
24	sessions	0001_initial	2026-05-25 02:38:46.051083+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
639ys0zdlzmtaty67thyjm6y39ntczsz	.eJxVjEEOwiAQAP_C2RAorIBH730DWXZXqZo2Ke3J-HdD0oNeZybzVhn3rea9yZonVhdl1emXFaSnzF3wA-f7ommZt3Uquif6sE2PC8vrerR_g4qt9m00zGhMZOvJQkIxDI4Ab0YKuCEGIhqAUXz0Es5FLISCGBw4H1JSny_r8Tf2:1wLh1T:WECeEaJl8KnmuRKdzFVvjE3v1U3EIKnqIno_xjNtVJY	2026-05-23 14:43:11.214+02
yfzc43qx80yxltb7ab33d3pt5qwfs7mi	.eJxVjEEOwiAQAP_C2RAorIBH730DWXZXqZo2Ke3J-HdD0oNeZybzVhn3rea9yZonVhdl1emXFaSnzF3wA-f7ommZt3Uquif6sE2PC8vrerR_g4qt9m00zGhMZOvJQkIxDI4Ab0YKuCEGIhqAUXz0Es5FLISCGBw4H1JSny_r8Tf2:1wQrBh:bN7sRCIE4RFSkngteQ8z0tsq-LnknRzi-c7s3dUCZs0	2026-06-06 20:35:05.19+02
\.


--
-- Name: BookShop_book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."BookShop_book_id_seq"', 9, true);


--
-- Name: BookShop_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."BookShop_category_id_seq"', 1, true);


--
-- Name: BookShop_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."BookShop_user_groups_id_seq"', 1, false);


--
-- Name: BookShop_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."BookShop_user_id_seq"', 1, true);


--
-- Name: BookShop_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."BookShop_user_user_permissions_id_seq"', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 32, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 8, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: BookShop_book BookShop_book_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_book"
    ADD CONSTRAINT "BookShop_book_pkey" PRIMARY KEY (id);


--
-- Name: BookShop_category BookShop_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_category"
    ADD CONSTRAINT "BookShop_category_pkey" PRIMARY KEY (id);


--
-- Name: BookShop_user BookShop_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user"
    ADD CONSTRAINT "BookShop_user_email_key" UNIQUE (email);


--
-- Name: BookShop_user_groups BookShop_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_groups"
    ADD CONSTRAINT "BookShop_user_groups_pkey" PRIMARY KEY (id);


--
-- Name: BookShop_user_groups BookShop_user_groups_user_id_group_id_128d91d6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_groups"
    ADD CONSTRAINT "BookShop_user_groups_user_id_group_id_128d91d6_uniq" UNIQUE (user_id, group_id);


--
-- Name: BookShop_user BookShop_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user"
    ADD CONSTRAINT "BookShop_user_pkey" PRIMARY KEY (id);


--
-- Name: BookShop_user_user_permissions BookShop_user_user_permi_user_id_permission_id_adfd2433_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_user_permissions"
    ADD CONSTRAINT "BookShop_user_user_permi_user_id_permission_id_adfd2433_uniq" UNIQUE (user_id, permission_id);


--
-- Name: BookShop_user_user_permissions BookShop_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_user_permissions"
    ADD CONSTRAINT "BookShop_user_user_permissions_pkey" PRIMARY KEY (id);


--
-- Name: BookShop_user BookShop_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user"
    ADD CONSTRAINT "BookShop_user_username_key" UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: BookShop_book_category_id_b046eee5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_book_category_id_b046eee5" ON public."BookShop_book" USING btree (category_id);


--
-- Name: BookShop_category_slug_89506b63; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_category_slug_89506b63" ON public."BookShop_category" USING btree (slug);


--
-- Name: BookShop_category_slug_89506b63_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_category_slug_89506b63_like" ON public."BookShop_category" USING btree (slug varchar_pattern_ops);


--
-- Name: BookShop_user_email_f445e2f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_user_email_f445e2f7_like" ON public."BookShop_user" USING btree (email varchar_pattern_ops);


--
-- Name: BookShop_user_groups_group_id_1c98c137; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_user_groups_group_id_1c98c137" ON public."BookShop_user_groups" USING btree (group_id);


--
-- Name: BookShop_user_groups_user_id_c1849577; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_user_groups_user_id_c1849577" ON public."BookShop_user_groups" USING btree (user_id);


--
-- Name: BookShop_user_user_permissions_permission_id_97eb9543; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_user_user_permissions_permission_id_97eb9543" ON public."BookShop_user_user_permissions" USING btree (permission_id);


--
-- Name: BookShop_user_user_permissions_user_id_69a625d2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_user_user_permissions_user_id_69a625d2" ON public."BookShop_user_user_permissions" USING btree (user_id);


--
-- Name: BookShop_user_username_ec00af86_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BookShop_user_username_ec00af86_like" ON public."BookShop_user" USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: BookShop_book BookShop_book_category_id_b046eee5_fk_BookShop_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_book"
    ADD CONSTRAINT "BookShop_book_category_id_b046eee5_fk_BookShop_category_id" FOREIGN KEY (category_id) REFERENCES public."BookShop_category"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: BookShop_user_groups BookShop_user_groups_group_id_1c98c137_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_groups"
    ADD CONSTRAINT "BookShop_user_groups_group_id_1c98c137_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: BookShop_user_groups BookShop_user_groups_user_id_c1849577_fk_BookShop_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_groups"
    ADD CONSTRAINT "BookShop_user_groups_user_id_c1849577_fk_BookShop_user_id" FOREIGN KEY (user_id) REFERENCES public."BookShop_user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: BookShop_user_user_permissions BookShop_user_user_p_permission_id_97eb9543_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_user_permissions"
    ADD CONSTRAINT "BookShop_user_user_p_permission_id_97eb9543_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: BookShop_user_user_permissions BookShop_user_user_p_user_id_69a625d2_fk_BookShop_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookShop_user_user_permissions"
    ADD CONSTRAINT "BookShop_user_user_p_user_id_69a625d2_fk_BookShop_" FOREIGN KEY (user_id) REFERENCES public."BookShop_user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_BookShop_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_BookShop_user_id" FOREIGN KEY (user_id) REFERENCES public."BookShop_user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict ylVtSShaRtwu7foGSTklCN4vcufnOiIc0d0jC5uBr9XhsDT3MQrRyrgUv30NjkK

