[pytest]
DJANGO_SETTINGS_MODULE = BookShop.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = --cov=. --cov-report=term-missing --cov-config=.coveragerc
cache_dir = /tmp/bookshop-pytest-cache
