# Generated by Django 6.0.7 on 2026-08-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("damaged", "Damaged"),
                    ("lost", "Lost"),
                    ("stolen", "Stolen"),
                    ("defective", "Defective"),
                    ("obsolete", "Obsolete"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("receipt", "Receipt"),
                    ("reservation", "Reservation"),
                    ("reservation_release", "Reservation release"),
                    ("sale", "Sale"),
                    ("return", "Return"),
                    ("write_off", "Write-off"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=30,
            ),
        ),
    ]
