# Generated by Django 6.0.7 on 2026-08-11 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("inventory", "0002_stockmovement_reason_alter_inventory_book_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("order_id", models.UUIDField()),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_return", "Customer return"),
                            ("damaged_return", "Damaged return"),
                            ("wrong_item", "Wrong item"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="stockmovement",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("damaged", "Damaged"),
                    ("lost", "Lost"),
                    ("stolen", "Stolen"),
                    ("defective", "Defective"),
                    ("obsolete", "Obsolete"),
                    ("other", "Other"),
                    ("stocktake_correction", "Stocktake correction"),
                    ("data_correction", "Data correction"),
                    ("found_stock", "Found stock"),
                    ("customer_return", "Customer return"),
                    ("damaged_return", "Damaged return"),
                    ("wrong_item", "Wrong item"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "created_at"],
                name="inventory_s_movemen_ed5291_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["book", "created_at"], name="inventory_s_book_id_afdc0c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("reserved_quantity"))),
                name="inventory_quantity_gte_reserved",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreturn",
            index=models.Index(
                fields=["order_id", "created_at"], name="inventory_s_order_i_bbc870_idx"
            ),
        ),
        migrations.AddField(
            model_name="stockreturnitem",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="books.book"
            ),
        ),
        migrations.AddField(
            model_name="stockreturnitem",
            name="stock_return",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.stockreturn",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreturnitem",
            constraint=models.UniqueConstraint(
                fields=("stock_return", "book"), name="unique_book_per_stock_return"
            ),
        ),
    ]
