# Generated by Django 6.0.7 on 2026-08-11 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_book_author_and_more'),
        ('inventory', '0003_stockreturn_stockreturnitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Stock movement', 'verbose_name_plural': 'Stock movements'},
        ),
        migrations.AlterModelOptions(
            name='stockreturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Return', 'verbose_name_plural': 'Returns'},
        ),
        migrations.AlterModelOptions(
            name='stockreturnitem',
            options={'verbose_name': 'Return item', 'verbose_name_plural': 'Return items'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Reserved quantity'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('reservation', 'Reservation'), ('reservation_release', 'Reservation release'), ('sale', 'Sale'), ('return', 'Return'), ('write_off', 'Write-off'), ('adjustment', 'Adjustment')], max_length=30, verbose_name='Movement type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('stolen', 'Stolen'), ('defective', 'Defective'), ('obsolete', 'Obsolete'), ('other', 'Other'), ('stocktake_correction', 'Stocktake correction'), ('data_correction', 'Data correction'), ('found_stock', 'Found stock'), ('customer_return', 'Customer return'), ('damaged_return', 'Damaged return'), ('wrong_item', 'Wrong item')], max_length=30, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='order_id',
            field=models.UUIDField(verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='reason',
            field=models.CharField(choices=[('customer_return', 'Customer return'), ('damaged_return', 'Damaged return'), ('wrong_item', 'Wrong item')], max_length=30, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='stockreturnitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='stockreturnitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockreturnitem',
            name='stock_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreturn', verbose_name='Return'),
        ),
    ]
