# Generated by Django 6.0.7 on 2026-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.UUIDField(unique=True)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
