# Generated by Django 6.0.3 on 2026-05-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0004_alter_category_options_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
