# Generated by Django 6.0.7 on 2026-08-11 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_book_author_and_more'),
        ('reservations', '0002_reservation_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='reservationitem',
            options={'verbose_name': 'Reservation item', 'verbose_name_plural': 'Reservation items'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('PAYMENT_FAILED', 'Payment failed'), ('ORDER_CANCELLED', 'Order cancelled'), ('RESERVATION_EXPIRED', 'Reservation expired'), ('MANUAL', 'Manual cancellation')], max_length=30, verbose_name='Cancellation reason'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='order_id',
            field=models.UUIDField(unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation', verbose_name='Reservation'),
        ),
    ]
